/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 046be31294f16dda664a676e54a4a23d)
interface __BaseEnv_CloudflareEnv {
	DB: D1Database;
	ASSETS: Fetcher;
	DEPLOYMENT_MODE: string;
	TZ: string;
	DATABASE_PROVIDER: string;
	JWT_SECRET: string;
	ENC_HASH: string;
	COOKIE_SECURE: string;
	ALLOW_FAMILY_SETUP: string;
	ENABLE_LOG: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends Partial<StringifyValues<Pick<Cloudflare.Env, "DEPLOYMENT_MODE" | "TZ" | "DATABASE_PROVIDER" | "JWT_SECRET" | "ENC_HASH" | "COOKIE_SECURE" | "ALLOW_FAMILY_SETUP" | "ENABLE_LOG">>> {}
}
